//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System;

namespace Evenimente
{
    public partial class Event
    {
        [Key]
        public int Id { get; set; }

        public string Name { get; set; }
        public string Description { get; set; }
        public string Place { get; set; }
        public string Hour { get; set; }
        public string BeginDate { get; set; }
        public string EndDate { get; set; }
        public string MinDateBirth { get; set; }
        public Nullable<int> NumberOfTickets { get; set; }
        public Nullable<int> Price { get; set; }
        public string Status { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> CategoryId { get; set; }
    }
}
